name: achiva
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.5.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  firebase_storage: ^12.3.0
  firebase_database: ^11.1.3
  firebase_auth: ^5.2.1
  image_picker: ^1.1.2
  cloud_firestore: ^5.4.1
  intl: ^0.19.0
  mockito: ^5.4.4
  build_runner: ^2.4.12
  shared_preferences: ^2.3.2
  internet_connection_checker: ^1.0.0+1
  awesome_dialog: ^3.2.1
  pin_code_fields: ^8.0.1
  http: 1.2.2 
  timelines: ^0.1.0
  firebase_app_check: ^0.3.1+3
  uuid: ^4.5.1
  path_provider: ^2.1.4
  permission_handler: ^10.2.0
  share_plus: ^10.1.1
  another_flushbar: ^1.12.30
  rxdart: ^0.28.0
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  flutter_gemini: ^2.0.3






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  test: ^1.21.0
  # fake_cloud_firestore: ^3.0.3 mock class for testing
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/images/
    - lib/images/logo.png
    - lib/images/chicken.png
    - lib/images/no-results.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
